globalCache:
  capacity: 1500

jerseyClient:
  timeout: 30s
  connectionTimeout: 1m

server:
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m %kvp%n%dwREx"
      target: stderr
      discardingThreshold: 0
  loggers:
    nl.knaw.huc: INFO
    org: WARN
    org.glassfish: ERROR
    com.jayway: ERROR

externalBaseUrl: ${BR_EXTERNAL_BASE_URL}

projects:
  - name: ${PROJECT}
    topTierBodyType: "Document"
    textType: NormalText
    annoRepo:
      containerName: ${PROJECT}
      uri: http://${ANNOREPO_HOST}:${ANNOREPO_PORT}
      cacheCapacity: 1000
      cacheThreshold: 500
    brinta:
      uri: http://${ELASTIC_HOST}:${ELASTIC_PORT}
      indices:
        - name: ${PROJECT}
          bodyTypes: ["Letter"]
          fields:
            - name: type
              type: keyword
            - name: identifier
              type: keyword
            - name: title
              type: keyword
            - name: subtitle
              type: keyword
            - name: author
              type: keyword
            - name: editor
              type: keyword
            - name: datePublished
              type: date
    views:
      - name: text
        anno:
          - path: "body.type"
            values: ["Letter"]
      - name: textNotes
        anno:
          - path: "body.type"
            values: ["Note"]
        findWithin:
          path: "body.type"
          value: "Note"
          groupBy: "body.n"
