networks:
  bridge_network:
    driver: bridge

services:
  textsurf:
    container_name: textsurf
    image: registry.diginfra.net/tt/textsurf:${TEXTSURF_VERSION}
    environment:
      UNLOADTIME: ${TEXTSURF_UNLOADTIME}
    networks:
      - bridge_network
    extra_hosts:
      - ${HOSTNAME}:host-gateway
    expose:
      - ${TEXTSURF_PORT}
    ports:
      - "${TEXTSURF_PORT}:8080"
    restart: unless-stopped
    volumes:
      - ./data/textsurf:/data

  annorepo:
    container_name: annorepo
    depends_on:
      - mongodb
    environment:
      AR_EXTERNAL_BASE_URL: ${ANNOREPO_URL}
      AR_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/
      AR_DB_NAME: annorepo
      AR_PAGE_SIZE: 100
      AR_WITH_AUTHENTICATION: yes
      AR_ROOT_API_KEY: ${ANNOREPO_ROOT_API_KEY}
    expose:
      - ${ANNOREPO_PORT}
    ports:
      - "${ANNOREPO_PORT}:8080"
      - "${ANNOREPO_CTL_PORT}:8081"
    healthcheck:
      test: "curl -fail http://localhost:${ANNOREPO_CTL_PORT}/healthcheck"
      interval: 1s
      retries: 20
      start_period: 1s
      timeout: 1s
    image: ghcr.io/knaw-huc/annorepo-server:${ANNOREPO_VERSION}
    networks:
      - bridge_network
    extra_hosts:
      - ${HOSTNAME}:host-gateway
    restart: unless-stopped
    tty: true

  broccoli:
    container_name: broccoli
    depends_on:
      annorepo:
        condition: service_healthy
      elastic:
        condition: service_started
    environment:
      BASEURL: ${BASE_URL}
      PROJECT: ${PROJECT}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_PORT: ${ELASTIC_PORT}
      ANNOREPO_HOST: ${ANNOREPO_HOST}
      ANNOREPO_PORT: ${ANNOREPO_PORT}
      BR_EXTERNAL_URL: ${BASE_URL}:${BROCCOLI_PORT}
      BR_EXTERNAL_BASE_URL: ${BASE_URL}:${BROCCOLI_PORT}
      TIER0: ${TIER0}
      TIER1: ${TIER1}
    expose:
      - ${BROCCOLI_PORT}
    ports:
      - "${BROCCOLI_PORT}:8080"
    image: ghcr.io/knaw-huc/broccoli:${BROCCOLI_VERSION}
    networks:
      - bridge_network
    extra_hosts:
      - ${HOSTNAME}:host-gateway
    restart: unless-stopped
    volumes:
      - ./config/broccoli/config.yml:/app/broccoli/config.yml:ro

  elastic:
    # see https://docs.rancherdesktop.io/how-to-guides/increasing-open-file-limit/
    # needed to run the stack on macos under rancher desktop
    container_name: elastic
    environment:
      elasticport: ${ELASTIC_PORT}
      node.name: br01
      cluster.initial_master_nodes: br01
      cluster.name: elastic-cluster
      bootstrap.memory_lock: ${ELASTIC_MEMORY_LOCK}
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms${ELASTIC_JAVA_MEM}m -Xmx${ELASTIC_JAVA_MEM}m"
    expose:
      - ${ELASTIC_PORT}
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    networks:
      - bridge_network
    extra_hosts:
      - ${HOSTNAME}:host-gateway
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data

  mongodb:
    command: --quiet  # suppress checkpoint logging (every minute)
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    expose:
      - ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:27017"
    image: docker.io/mongo:${MONGODB_VERSION}
    networks:
      - bridge_network
    extra_hosts:
      - ${HOSTNAME}:host-gateway
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db

  cantaloupe:
    container_name: cantaloupe
    image: uclalibrary/cantaloupe:${CANTALOUPE_VERSION}
    environment:
        HEAP_PERCENTAGE: 50
        CANTALOUPE_HTTP_ENABLED: "true"
        CANTALOUPE_HTTPS_ENABLED: "false"
        CANTALOUPE_BASE_URI: ${CANTALOUPE_URL}
        CANTALOUPE_SLASH_SUBSTITUTE: "|"
        CANTALOUPE_LOG_APPLICATION_LEVEL: info
        CANTALOUPE_LOG_APPLICATION_CONSOLEAPPENDER_ENABLED: "true"
        CANTALOUPE_LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    expose:
      - ${CANTALOUPE_PORT}
    ports:
      - "${CANTALOUPE_PORT}:8182"
    networks:
      - bridge_network
    volumes:
      - ./data/cantaloupe:/imageroot
      #TODO: log and cache is not persistent for now
    restart: unless-stopped
