# Configuration for stam translatetext
# Normalizes text by removing hyphenation and linebreaks (assumes UNIX line endings)

id_suffix = "normal"

[[rules]]
source = "\n"
target = " "
left = "/\\p{L}/"
right = "/\\p{L}/"

[[rules]]
source = "-\n"
target = ""
left = "/\\p{L}/"
right = "/\\p{L}/"

[[rules]]
source = "¬\n"
target = ""
left = "/\\p{L}/"
right = "/\\p{L}/"
