zoneBased: true

models:
  - editem-about
  - editem-letter
  - editem-artworklist
  - editem-biolist
  - editem-bibliolist
templates:
  - about
  - letter
  - biolist
  - bibliolist
  - artworklist
adaptations:
  - ji
templateTrigger: "?editem@template"
adaptationTrigger: "?editem@adaptation"
procins: true
sectionModel: 
  model: I
  levels:
  - folder
  - file
  - chunk
  backMatter: apparatus
