excludedFolders:
  intro: true

switches:
  dev:
    server: 'http://localhost:8087'
    iiifPath: ''
    iiifPathEsc: ''
    ext: 'jpg'
    extm: 'jpeg'
    hilo: 'thumb'
  preview:
    server: '[baseUri]'
    iiifPath: '[title]/'
    iiifPathEsc: '[title]|'
    ext: 'jpg'
    extm: 'jpg'
    hilo: 'scans'
  prod:
    server: 'https://data.vangogh.huygens.knaw.nl'
    iiifPath: ''
    iiifPathEsc: ''
    ext: 'jpg'
    extm: 'jpg'
    hilo: 'scans'

constants:
  context: 'http://iiif.io/api/presentation/3/context.json'
  profile: 'http://iiif.io/api/image/3/level1.json'
  rightsCC0: 'http://creativecommons.org/publicdomain/zero/1.0/'
  providerId: 'https://www.vangoghmuseum.nl'
  providerLabelEn: "Van Gogh Museum"
  provHomepageId: 'https://www.vangoghmuseum.nl/en'
  provHomepageLabel: 'Homepage of the Van Gogh Museum'
  provLogoId: 'providerlogo.png'
  provLogoHeight: 270
  provLogoWidth: 288
  ext: 'jpg'
  iiifRoot: '«server»/iiif/3/«iiifPathEsc»«hilo»|'
  iiifParams: '/full/max/0/default'
  manifestRoot: '«server»/files/«iiifPath»static/manifests/'
  logoRoot: '«server»/files/«iiifPath»static/logo'
  metaRoot: '«server»/files/«iiifPath»static/meta'

manifestLevel: file
zoneBased: true

macros:
  manifestUrl: '«manifestRoot»{folder}/{file}.json'
  canvasUrl: '«manifestRoot»{folder}/{file}.json/canvas/«iiifPath»pages/{page}'
  pageUrl: '«iiifRoot»pages|{page}.«ext»«iiifParams».«ext»'

mirador:
  manifests: '«server»/files/[title]/static/manifests/letters/'
  example: 'ii001.json'

scans:
  manifestUrl:
    letter:
      vars:
        folder: folder.folder
        file: file.file
      value: '<manifestUrl>'
  canvasUrl:
    page:
      vars:
        folder: folder.folder
        file: file.file
        page: facsfile
      value: 'checkPage:‖{file}‖<canvasUrl>' 
    letter:
        vars:
          folder: folder.folder
          file: file.file
          page: '-page.facsfile'
        value: 'checkPage:‖{file}‖<canvasUrl>' 
  pageUrl:
    page:
      vars:
        file: file.file
        page: facsfile
      value: 'checkPage:‖{file}‖<pageUrl>' 
  xywh:
    page:
      vars:
        page: facsfile
        region: facsregion
      value: 'px:‖{page}‖{region}'
  prev:
    page:
      vars:
        node: '=-1'
      value: '{node}' 
    letter:
      vars:
        node: '=-1'
      value: '{node}' 
  next:
    page:
      vars:
        node: '=+1'
      value: '{node}' 
    letter:
      vars:
        node: '=+1'
      value: '{node}' 

templates:
  # manifestLevel:
  pageSequence:
    "@context": «context»
    manifestInventory: '<manifestUrl>'
    type: Manifest
    label:
      en:
      - 'Letters'
    metadata:
    - label:
        en:
        - Filename
      value:
        en:
        - '{folder}/{file}.json'
    summary:
      en:
      - 'Letters'
    rights: «rightsCC0»
    provider:
    - id: '«providerId»'
      type: Agent
      label:
      - en: '«providerLabelEn»'
      homepage:
        - id: '«provHomepageId»'
          type: Text
          label:
          - en: '«provHomepageLabel»'
          format: text/html
      logo:
        - id: '«logoRoot»/«provLogoId»'
          type: Image
          format: image/«extm»
          height: '«provLogoHeight»'
          width: '«provLogoWidth»'

  # canvasLevel
  pageItem:
    id: '<canvasUrl>'
    type: Canvas
    label: 
      en:
      - '{page}'
    height: '{height}'
    width: '{width}'
    items:
    - id: '<canvasUrl>/annotationpage'
      type: AnnotationPage
      items:
      - id: '<canvasUrl>/anno'
        type: Annotation
        motivation: painting
        body:
          id: '<pageUrl>'
          type: Image
          height: '{height}'
          width: '{width}'
          service:
          - 'id': '«iiifRoot»pages|{page}.«ext»'
            'type': ImageService3
            profile: '«profile»'
          format: image/«extm»
        target: '<canvasUrl>'
